# Typos configuration for r2x-core
# See https://github.com/crate-ci/typos for more information
[files]
extend-exclude = [
    "tests/*",
]

[default.extend-words]
# Pydantic core schema function name (not a typo)
ser = "ser"
