"""R2X ReEDS Plugin.

A plugin for parsing ReEDS (Regional Energy Deployment System) model data
into the R2X framework using infrasys components.
"""

from importlib.metadata import version

from loguru import logger

__version__ = version("r2x_reeds")

# Import getters to register them with r2x-core
from . import getters  # noqa: F401
from .models import (
    AnnualCapMode,
    EmissionRate,
    EmissionType,
    Fraction,
    FractionRange,
    FromTo_ToFrom,
    NonEmptyText,
    NonNegativeFloat,
    NonNegativeRange,
    Percentage,
    ReEDSBinarySwitch,
    ReEDSCapacityExpansion,
    ReEDSCapacityExpansionResource,
    ReEDSComponent,
    ReEDSConsumingTechnology,
    ReEDSConsumingTechnologyEconomics,
    ReEDSConsumingTechnologyPerformance,
    ReEDSDataCenterDemand,
    ReEDSDemand,
    ReEDSDispatchableCapacityExpansionResource,
    ReEDSElectrolyzerDemand,
    ReEDSEmission,
    ReEDSGenerator,
    ReEDSGeneratorEconomics,
    ReEDSGeneratorIdentity,
    ReEDSGeneratorOperatingConstraints,
    ReEDSGeneratorPerformance,
    ReEDSGeneratorSupplyCurve,
    ReEDSH2Pipeline,
    ReEDSH2Storage,
    ReEDSHydroGenerator,
    ReEDSInitialCapacity,
    ReEDSInterface,
    ReEDSPlanningPeriod,
    ReEDSPlanningSwitches,
    ReEDSPlantCharacteristics,
    ReEDSRegion,
    ReEDSRepresentativeTimepoint,
    ReEDSReserve,
    ReEDSReservePercentages,
    ReEDSReserveRegion,
    ReEDSResourceClass,
    ReEDSStorage,
    ReEDSStorageCapacityExpansionResource,
    ReEDSStorageDuration,
    ReEDSStorageDurationOverride,
    ReEDSThermalGenerator,
    ReEDSTransmissionLine,
    ReEDSVariableCapacityExpansionResource,
    ReEDSVariableGenerator,
    ReserveDirection,
    ReserveType,
    TransmissionLineType,
)
from .parser import ReEDSParser
from .plugin_config import ReEDSConfig
from .upgrader import ReEDSUpgrader

logger.disable("r2x_reeds")

latest_commit = "401c0bb15cbf93d2ff9696b14b799edad763247a"

__all__ = [
    "AnnualCapMode",
    "EmissionRate",
    "EmissionType",
    "Fraction",
    "FractionRange",
    "FromTo_ToFrom",
    "NonEmptyText",
    "NonNegativeFloat",
    "NonNegativeRange",
    "Percentage",
    "ReEDSBinarySwitch",
    "ReEDSCapacityExpansion",
    "ReEDSCapacityExpansionResource",
    "ReEDSComponent",
    "ReEDSConfig",
    "ReEDSConsumingTechnology",
    "ReEDSConsumingTechnologyEconomics",
    "ReEDSConsumingTechnologyPerformance",
    "ReEDSDataCenterDemand",
    "ReEDSDemand",
    "ReEDSDispatchableCapacityExpansionResource",
    "ReEDSElectrolyzerDemand",
    "ReEDSEmission",
    "ReEDSGenerator",
    "ReEDSGeneratorEconomics",
    "ReEDSGeneratorIdentity",
    "ReEDSGeneratorOperatingConstraints",
    "ReEDSGeneratorPerformance",
    "ReEDSGeneratorSupplyCurve",
    "ReEDSH2Pipeline",
    "ReEDSH2Storage",
    "ReEDSHydroGenerator",
    "ReEDSInitialCapacity",
    "ReEDSInterface",
    "ReEDSParser",
    "ReEDSPlanningPeriod",
    "ReEDSPlanningSwitches",
    "ReEDSPlantCharacteristics",
    "ReEDSRegion",
    "ReEDSRepresentativeTimepoint",
    "ReEDSReserve",
    "ReEDSReservePercentages",
    "ReEDSReserveRegion",
    "ReEDSResourceClass",
    "ReEDSStorage",
    "ReEDSStorageCapacityExpansionResource",
    "ReEDSStorageDuration",
    "ReEDSStorageDurationOverride",
    "ReEDSThermalGenerator",
    "ReEDSTransmissionLine",
    "ReEDSUpgrader",
    "ReEDSVariableCapacityExpansionResource",
    "ReEDSVariableGenerator",
    "ReserveDirection",
    "ReserveType",
    "TransmissionLineType",
    "__version__",
]
